name: Auto Version

on:
  push:
    branches: [main]
    paths-ignore:
      - 'VERSION'
      - '**.md'

jobs:
  auto-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip version]')"
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current version
        id: current-version
        run: |
          # Get current version from latest tag instead of VERSION file
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          CURRENT_VERSION=${LATEST_TAG#v}
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Latest tag found: $LATEST_TAG"
          echo "Current version extracted: $CURRENT_VERSION"

      - name: Determine version increment
        id: version-type
        run: |
          # Analyze commit message to determine increment type
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          
          if [[ "$COMMIT_MSG" =~ (\[major\]|\[MAJOR\]|\[breaking\]|\[BREAKING\]|BREAKING.CHANGE) ]]; then
            echo "increment=major" >> $GITHUB_OUTPUT
            echo "Version increment: MAJOR"
          elif [[ "$COMMIT_MSG" =~ (\[minor\]|\[MINOR\]|\[feature\]|\[FEATURE\]|feat:) ]]; then
            echo "increment=minor" >> $GITHUB_OUTPUT
            echo "Version increment: MINOR"
          else
            echo "increment=patch" >> $GITHUB_OUTPUT
            echo "Version increment: PATCH"
          fi

      - name: Increment version
        id: new-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.current }}"
          INCREMENT_TYPE="${{ steps.version-type.outputs.increment }}"
          
          echo "🔍 DEBUG: Starting version calculation"
          echo "Current version: $CURRENT_VERSION"
          echo "Increment type: $INCREMENT_TYPE"
          
          # Extract version components (major.minor.patch)
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          echo "Parsed - MAJOR: $MAJOR, MINOR: $MINOR, PATCH: $PATCH"
          
          # Increment based on type
          case $INCREMENT_TYPE in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              echo "MAJOR increment: $MAJOR.0.0"
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              echo "MINOR increment: $MAJOR.$MINOR.0"
              ;;
            "patch")
              PATCH=$((PATCH + 1))
              echo "PATCH increment: $MAJOR.$MINOR.$PATCH"
              ;;
          esac
          
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "✅ Final new version: $NEW_VERSION"

      - name: Create and push tag
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.version }}"
          TAG_NAME="v$NEW_VERSION"
          
          # Check if tag already exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "⚠️  Tag $TAG_NAME already exists, skipping tag creation"
            echo "This might happen if the workflow runs multiple times"
          else
            git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
            git push origin "$TAG_NAME"
            echo "✅ Created and pushed tag: $TAG_NAME"
          fi

      - name: Release information
        run: |
          INCREMENT_TYPE="${{ steps.version-type.outputs.increment }}"
          NEW_VERSION="${{ steps.new-version.outputs.version }}"
          
          echo "✅ Tag created: v$NEW_VERSION"
          echo "🚀 CD workflow will be triggered automatically by the tag"
          echo "ℹ️  VERSION file remains unchanged to avoid extra commits"
          
          if [[ "$INCREMENT_TYPE" == "minor" || "$INCREMENT_TYPE" == "major" ]]; then
            echo "🎉 GitHub Release will be created by CD workflow for $INCREMENT_TYPE version"
          else
            echo "ℹ️  No GitHub Release for patch versions (CD will still build Docker images)"
          fi